### ISSUE TITLE
How much ammo do I have?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#10]
It's all fine and good to swap to the cool new gun I picked up, but if I don't have any ammo, I'm just standing getting around shot by mall cops taking it on authority that the new things are cool

**Comment by kallman1206** [comment]
Especially scrolling through my guns, it's annoying to be being shot by three guys and just "Click", scroll, "click", scroll, "click", scroll, before finally getting back to the sidearm to shoot them with...

**Comment by Maxwolf** [comment]
I will add HUD elements to show health and current ammo count for the weapon you have selected.

**Comment by kallman1206** [comment]
With health being regenerating, I think some kind of fuzzy graphic is better than a number, "Greater than 50%, less than 75% kind of deal. My $0.02.

**Comment by Maxwolf** [comment]
Fixed!

![screenshot001](https://cloud.githubusercontent.com/assets/6830398/16544915/09591ff2-40cc-11e6-9879-288a1c9f8ff2.png)
