### ISSUE TITLE
Typo: 12-gauge shotgun > 12-guage

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#11]

**Comment by Maxwolf** [comment]
Gotta love spelling mistakes. Will take care of it!

**Comment by Maxwolf** [comment]
Changed text to .12 Guage Shotgun for both the long barrel mossberg and the sawed-off double barrel.

**Comment by kallman1206** [comment]
Isn't the correct spelling "gauge" though, max? Sorry if I titled this in an unclear way >.>

**Comment by Maxwolf** [comment]
.12 Gauge Shotgun NOT Guage
