### ISSUE TITLE
Where'd the two guys having seizures go?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#12]
first I wonder why there's two dudes writhing in pain on the floor before I hand over some square pigs, then I wonder where they've gone when the bullets start flying.

Plus I think I dodged the hypermarket owner boss lady totally unintentionally, oops.

**Comment by Maxwolf** [comment]
Yeah you can skip her not forced will come up with something creative later
for sure

**Comment by Maxwolf** [comment]
Remove the seizure people they serve no purpose. Make it so the player has to go into the room and encounter boss lady to unlock a door which will also be our tutorial to the player for how this system works. This will be better than using shield generator which can be capped from the window and avoiding her completely.

**Comment by Maxwolf** [comment]
Removed the sick people from Charon.
