### ISSUE TITLE
Ugly's place is a big dark warren

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#13]
I made the mistake of trying to explore back there. Want to just stick a closed door behind him 'til you populate the place?

**Comment by Maxwolf** [comment]
Yeah the base is empty right now bit sure what look I want for him

**Comment by kallman1206** [comment]
Miss July 1960. The stuff that was going to be in lockers when the truck was huge. Unless you're saving that for the crashed one... "Can you believe, the company was going to build a fleet of these for us to drive? Then the VP changed and there were a few minor cost - saving measures..."

**Comment by Maxwolf** [comment]
Interesting idea there with the miss july 1960. I had original idea to make
like a bar/strip club similar to something Quark would have on Deep Space
9. The more I work on it though it seems that something like a bar +
mechanic shop might be cool.

On Fri, Jun 24, 2016 at 2:30 PM, kallman1206 <notifications@github.com>
wrote:

> Miss July 1960. The stuff that was going to be in lockers when the truck
> was huge. Unless you're saving that for the crashed one... "Can you
> believe, the company was going to build a fleet of these for us to drive?
> Then the VP changed and there were a few minor cost - saving measures..."
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/FoxBytes/SpaceTruckerBugs/issues/13#issuecomment-228466916>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGg5PqSlPyqLoY-cM7jSq5EX4CizSddYks5qPEyIgaJpZM4I9kJU>
> .
>



-- 
Ron 'Maxwolf' McDowell

**Comment by Maxwolf** [comment]
Regenerated his level, made it much more interactive. Instead of just visiting here you actually have to fight through the Americans to get to Ugly as he gets shot at the end of the level.

**Comment by kallman1206** [comment]
Slap a bathroom on there with a members only hackable door inside, that one stall looks slightly cleaner. "Aren't you glad you paid $200 for the bathroom cleaned once a week instead of once a month?"
