### ISSUE TITLE
Is the nationality of every satellite classified?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#14]
The teleporter never has anything to tell me! I guess it's just fluff anyhow, but just pointing out whatever I see. (Especially with Ugly specifically telling us the americans are running stuff out here on nix right beforehand, too...)

**Comment by Maxwolf** [comment]
Nah they are not classified, I will have the information from locations list to describes what type of research and or the purpose of the facility, it's nationality (with a flag and text), and how many people approximate are inside of the facility.

**Comment by kallman1206** [comment]
So just a "not implemented yet", eh? Let me just pile on another 1500 little improvements ;)

**Comment by Maxwolf** [comment]
Yeah I wanted to get it working in some primitive state like it is now for the prototype and then we can refine and iterate on it like the ideas listed so far from Fox and you.

**Comment by Maxwolf** [comment]
Removed these blurbs of text from the teleporter computer. Now we have the minimap, title, picture of the moon, and that is it on two giant monitors. Keeping it simple for the players.
