### ISSUE TITLE
"Exit" in the "the game is not paused" menu keeps catching me by mistake

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#15]
Do you want to slap a confirmation dialog on there, or at least amend it to "Exit game" instead of just "Exit"? <3

**Comment by Maxwolf** [comment]
I will put a confirmation dialog on the exit so it is not abrupt. Will say something like "You will lose all progress on this act unless you advance through it. Do you really want to quit? Y/N"

**Comment by Maxwolf** [comment]
Starting on this now

**Comment by Maxwolf** [comment]
Created dialog and got it rigged up to exit game button on the main menu. I also renamed it from exit to exit game so what it does it very clear to the user.

![image](https://cloud.githubusercontent.com/assets/6830398/17267303/60f99400-55ba-11e6-8167-2d7750adcde0.png)
