### ISSUE TITLE
Friendly scientist voiceover in twisted dimension

### ISSUE THREAD

**Issue by Maxwolf** [FoxBytes/SpaceTruckerBugs#156]
If the player kills more than 50% of the scientists then the twisted dimension level will be silent and the player will get no assistance. However, if the player lets the scientists live they will open up channel and talk to the player and help guide them through the level and put target markers on things so it's much easier.

This is a reward for the player for showing mercy to the scientists and not killing them, and an obvious punishment for those that kill them.

**Comment by Maxwolf** [comment]
Science guy in a ready room, over the intercom. "That's experimental technology! There's no telling what will happen if you shut it off improperly, and I'm not turning it off properly until you get the fuck out of orbit!"

**Comment by Maxwolf** [comment]
Or a "time works differently there" side mission (not that you're focusing on that atm anyways), where it replays the ominous radio transmissions from the beginning, give you false hope you could get back before it all went for hell

**Comment by Maxwolf** [comment]
"Well ok it still threw you through a rift, but I'm pretty sure there's going to be a way back, which I wouldn't promise if you'd just snapped parts off the damned thing."

**Comment by kallman1206** [comment]
You're up to a hundred fifty of these? Clearly I need to snag a newer build and check stuff out :)

In order for it to be a real help, build traps into the other dimension, maybe? Like, bulbous things spawn bridges if you kill them, but identical ones are full of abominations, or make you go the long way by moving stuff to inconvenient places, and the science dudes can tell you which ones to pop?

**Comment by Maxwolf** [comment]
There is an 'alien' keycard system where there are floating spooky symbols that the player needs to match up to correct totem. The scientist could put target markers on these to make it easier and help the player know which card goes to what totem removing guess work.

**Comment by Maxwolf** [comment]
Not happening since DimensionX was removed since it would take to long to integrate it into the game at this current time.

**Comment by kallman1206** [comment]
Aw, but it's so [theoretically] cool! It's entirely built of unique resources, but when there's just a handful of maps...

Ah, well. You've been in this boat before, ultimately you know what content it makes sense to prioritize.

**Comment by Maxwolf** [comment]
I agree the idea is cool and I like it, but when playing the level it feels cheap and forces compared to the other which have months of design work poured into them.
