### ISSUE TITLE
Should the truck teleporters have their particles when no destination's been selected?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#16]
Want to train the player on when teleportation is valid, right? When you've come to talk to ugly in chapter 2, his pad doesn't show anything when it doesn't go anywhere (ie. before he's given you the mission), but yours are lit up regardless of if you've selected a satellite to transport to.

**Comment by Maxwolf** [comment]
You are right I should disable the teleporter light tube that shows up unless you have a destination currently set. That would make more sense to the player that they have a location locked into the device and are ready to rock and roll and teleport there.

**Comment by Maxwolf** [comment]
This is also getting fixed now. The new teleporter control panel is much more ergonomic and less imposing to new users with the big screens. When you select a target on the teleporter it will enable the pads for you to step on, turning the device off, running out of power, or clearing the target destination will disable the light columns.

**Comment by Maxwolf** [comment]
Teleporters no longer show the light column in the exact same manner as the recall counter-parts on levels to bring players back to the ship. This will re-enforce what we teach players about how to know when the teleporters are ready to be used.

When a target is selected they will show up.

![image](https://cloud.githubusercontent.com/assets/6830398/16649488/fd84e36c-43ed-11e6-83f0-607e8ed26795.png)
