### ISSUE TITLE
Sometimes gibs are acting crazy

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#17]
One of the mall cops shot sixteen feet in the air when I killed him on Charon, and here on Nix some kind of plywood chunk created when I blew up a shield generator seemed to be colliding with itself - was flipping back and forth flying through the air, vaguely reminiscent of a trash butterfly. I wish I'd been recording, it honestly looked amazing in the beautiful way only the truly unintentional can.

**Comment by Maxwolf** [comment]
While although mystical and beautiful I will find and destroy this mysterious wood box chunks. My guess is they are to light and just flipping out like crazy with almost no mass to make them fall down.

The people flying into the air I can definitely fix by hard locking them to the ground they are walking on, can also make them weigh like 900 pounds to stop them from going up very high if they are exploded up.

**Comment by Maxwolf** [comment]
Updating shield generator model to not be the exploding one like that and a nice mesh instead. That will stop that weirdness there. I will also make all the enemy corpses much heavier so they snap to the ground.

**Comment by Maxwolf** [comment]
Fixed the enemy corpses by making linear and angular dampening much stronger, I made gibs more bouncy and act like rubber so they will fly all over the place when you hit someone close up.

**Comment by Maxwolf** [comment]
Closing this since I fixed also the wood box chip pieces by doing the same thing.
