### ISSUE TITLE
Trash cans are inconsistant

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#19]
It's neat to be able to loot them, though why you can loot some and not others isn't obvious (did they just roll a "no treasure in me!" on the loot table?).

I'd prefer you could loot them all, and if it's a dud, it just spawns a "piece of trash" gib/sprite like the bullet casings.

**Comment by Maxwolf** [comment]
I think the trash can has health and is 'dying' and losing it's state when other things explode around it. Will investigate this but you are right they are inconsistent.

**Comment by kallman1206** [comment]
I think the one I noticed this on was through a wall from a shield generator, yeah. Makes sense it's in the blast radius. Could give it an "I'm dead" texture and drop the loot anyways, but would that let players loot it and then kill it to loot it again? I'd say to just give props eight million HP but that's a perverse incentive to try and score critical hits on shelving units to see if rockets pop out.

**Comment by Maxwolf** [comment]
Yeah trash cans had 1 health so they were getting destroyed by all the surrounding chaos almost always. This is fixed now and the only way to make the trash can Die() is by the player pressing their use key on it. Another thing I did was make the physics capsule for the trash can static so it will not move around the map and stay where level editors put them.
