### ISSUE TITLE
The formerly fucked-up stairs on Nix are still kinda fucked-up

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#20]
you CAN tell that they're stairs now, which is great! However, sometimes I can get up them and sometimes I can't. One of them I got stuck on the top step and had to descend, on it's neighbour, I couldn't start climbing the stairs until I approached from a different angle.

**Comment by Maxwolf** [comment]
That is so weird. I will have to just redo the physics calculations the default engine does for climbing over things. I guess the Russian Ivan that coded it is just stupid. Cannot seem to get stairs working right no matter their size of shape lawl.

Sorry about all that I will redo this and make it not shitty.

**Comment by kallman1206** [comment]
second time I came by, worked just fine. Bug's hiding now that I try to get a look at it.

**Comment by Maxwolf** [comment]
That is probably why I didn't notice. I also found that running up them by holding shift can sometimes literally launch you like a projectile. I was able to jump ontop of a guy and shoot down at his head this way.

**Comment by kallman1206** [comment]
do you still not have roof collisions? Run up stairs for out of bounds sounds just perfect, lol

**Comment by Maxwolf** [comment]
Yeah there is ceiling collisions on the inside of the level. Everything is one sided though so the outside of the level lets you see into it.

**Comment by Maxwolf** [comment]
Made it so you cannot take falling damage anymore or damage from running into things to fast. That stops half of the stupidness, the other will be to redo the logic for stepping up geometry.

**Comment by Maxwolf** [comment]
Regenerated level, and also fixed bug with stairs today by redoing all the physics interactions for going up and down slopes. This seems to have solved the issue.
