### ISSUE TITLE
Game either crashes or fails to load on initial launch

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#203]
The window launched from the installer's concluding "Launch Space Truckers" confirmation checkbox (calls itself a Configurator, iirc?) didn't launch the game for me.
Also 1599 x 899 is a spicy default render size, isn't it? Maybe that's just an odd thing with monitor autodetection or some such.

**Comment by Maxwolf** [comment]
Previous verion files caused this problem. Engine deleted it, so next start it was fine.

**Comment by Maxwolf** [comment]
Going to close this since it's not really a bug just side-effect of being an awesome tester with many versions of the game. Players on Steam will not encounter this problem with the finalized code base.
