### ISSUE TITLE
Game hangs on trying to skip initial seizure warning

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#204]
I was trying to skip past as you do, clicking and pressing space, and the window went grey and (not responding) as Windows do.
It did clear up after 10-15 seconds (while I went over here to enter this).

**Comment by Maxwolf** [comment]
Pretty sure your previous versions cache for models and physics were being regenerated and or removed by engine. That is why the startup must have taken longer than expected.

**Comment by kallman1206** [comment]
it was loading in the loading screen? How peculiar ;)

**Comment by Maxwolf** [comment]
Yeah the warning is the actual loading screen.

**Comment by Maxwolf** [comment]
Confirmed to be previous data from old saves messing with the engine. Closing issue since this will not be a problem in finalized code base that is released on Steam.
