### ISSUE TITLE
Sprite clipping through the doodad on your truck

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#207]
![image](https://cloud.githubusercontent.com/assets/4227353/17678441/f10e39cc-62eb-11e6-8a33-3cf6f49bf590.png)

Hopefully this is the right image. Anyhow, angling the view up and down makes it either be behind the glow effect or in front of it - or in fact, pop through at an angle. Side effect of the billboarding tech?

**Comment by Maxwolf** [comment]
Yeah this is a side effect of the billboarding tech and I cannot fix it without making it always look like it is popping out. I will leave it this way since it's not that big of a deal in the grand scheme. Thank you for noting it though!
