### ISSUE TITLE
Not allowed to close the door in the truck once it's open?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#208]
![image](https://cloud.githubusercontent.com/assets/4227353/17678585/93024eee-62ec-11e6-97ac-affae6dcef71.png)

The objective diamond is clear enough, that I have to get through the door and all, but it still tells me I can interact with this panel even though doing so has no effect.

**Comment by Maxwolf** [comment]
Will make it so the panel will stop highlighting after it's been triggered.

**Comment by Maxwolf** [comment]
Fixed! Buttons setup this way after being flipped will not show any text or interaction being possible anymore so the player doesn't think it is broken.
