### ISSUE TITLE
Truck lights lose and regain power seemingly at random?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#209]
I came back from being paused a few minutes to hear a bank of lights turn off and on again, just after I walked through the door to the forward section.

**Comment by kallman1206** [comment]
Also happens after running the "Test lamps" function of the announcer panel - does this actually put the ship in the "red alert" lights off mode?

**Comment by Maxwolf** [comment]
Alarm mode disables the lights yes. The lights were turning off when they lost enough power to stop operating, guessing some bug with their energy setup. I increased the amount of battery power and water on the ship to prevent this from happening as fast.

**Comment by Maxwolf** [comment]
Closed after testing with increased water and energy levels.
