### ISSUE TITLE
Hacking is strange

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#21]
I can't abort while it's underway, so when there's still an enemy in the room, seems strange I can do it at all. (He shot me repeatedly, shoved me along the face of the resonator data mainframe a few steps' worth while I was downloading)

**Comment by Maxwolf** [comment]
You can press escape key to close the PDA and kill the guy and go back to it. But I think a good mechanic would be to start hacking over or make the PDA detach when you are shot and hacking.

**Comment by kallman1206** [comment]
I thought I tried that. OK, good to know.

**Comment by Maxwolf** [comment]
FYI you can even goto other tabs and it will keep hacking. I think I need
to streamline this and or maybe make it like holding a map in Minecraft
where you can still walk and use your mouse?

On Fri, Jun 24, 2016 at 2:33 PM, kallman1206 <notifications@github.com>
wrote:

> I thought I tried that. OK, good to know.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/FoxBytes/SpaceTruckerBugs/issues/21#issuecomment-228467362>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGg5PpEjSNiP8CMlqF4sECSo1eNfizv0ks5qPE0ggaJpZM4I9l07>
> .
>



-- 
Ron 'Maxwolf' McDowell

**Comment by Maxwolf** [comment]
Fixed the PDA so it will automatically detach when you take any damage and cancel the current hack operation. This forces the player to clear the room before hacking a device.
