### ISSUE TITLE
Are rusty cogs really on-theme for decor?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#210]
I mean maybe if Ugly owns the truck and he's subtly being a dick about "You're just a low quality part to me", but they do seem pretty out of place with the vacuum of space a metre to the left of them.

**Comment by Maxwolf** [comment]
This is second time I have heard that, will remove them!

**Comment by Maxwolf** [comment]
Removed the rusty cogs from bridge.
