### ISSUE TITLE
Freaks me out to get "Energy Low" klaxon on out arrival at Charon

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#211]
Is it intentional to run out there? I forget from the prototype, think I raised a similar concern then.

Also I deactivated and reactivated the generator prior to locking in the course and what have you, so I might have wasted some fuel first, heh. "Use key all the things".

**Comment by Maxwolf** [comment]
It runs more often now because I made the ship move slower which means it consumes more energy to reach it's destination. This is apart of why I want to make it not a grid network and more like movie props I just trigger at various points based on act.

Some work to do here for sure.

**Comment by Maxwolf** [comment]
Increased the amount of water and battery power in the ship to stop this from happening.

**Comment by Maxwolf** [comment]
Increased the warning levels for low water and energy to be 5 instead of 10 to give a little bit more time.

**Comment by Maxwolf** [comment]
Closing after testing with increased energy and water levels on the ship.
