### ISSUE TITLE
Should turning off the annunciator panel with the toggle not deactivate the current klaxxon if there is one?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#212]

**Comment by Maxwolf** [comment]
I can make it do this! I was following alarm panel guidelines which state alarm is on if sensor system is offline and alarms stay on until human notifys them. However this is not a real alarm, and for a video game it would be better if it behaved this way.

Would feel more intuitive for sure.

**Comment by Maxwolf** [comment]
Will code it to remember the alarm was tripped and clear them when the all clear comes back.

**Comment by Maxwolf** [comment]
Not required anymore since alarm doesn't go off at random, when it does in the game such as during the freedom emitters destruction I want it to happen.
