### ISSUE TITLE
Mission briefing says "press any key to continue" but this isn't the case.

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#213]
I pressed D and it didn't go. Left click worked! Unless it totally did work and was just loading in the background.

**Comment by Maxwolf** [comment]
Yeah you are right it's not any key it's actually a pre-determined list lol. Escape, Space, enter, and mouse buttons.

**Comment by Maxwolf** [comment]
Maybe I should just say "Press enter to continue" ?

**Comment by Maxwolf** [comment]
Changed this up to say "Press enter to continue" and removed the other keys to keep things simple.
