### ISSUE TITLE
Hearing "Text is being printed on the screen" noise at the start of Charon Hypermarket level

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#214]
I was just looking at a lady by the teleporter - is there a console on the other side of the wall, maybe?

**Comment by Maxwolf** [comment]
It's above you! There is a log file reader up above, I can toggle the typing sound individually for consoles I kinda like it so leave it in but could disable if misleading/annoying.

**Comment by kallman1206** [comment]
I like the sounds when you can see it, don't know if it's too crazy to make it be quiet unless you've looked at it? Like, I liked hearing it when I went to the bridge on the truck.

**Comment by Maxwolf** [comment]
Decided to keep this, it's a nice audio cue that there is an interaction terminal nearby the more play-tests I saw.
