### ISSUE TITLE
Feature Request: Mark unread logs in the ship's computer in some way

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#215]
I assume more show up as the game progresses? Though maybe it's odd to do that, since they're supposed to be written by our player character, so of course he's seen them, right?

**Comment by Maxwolf** [comment]
Yeah it's more of a personal diary written by vlad and we let the player peek into it like that. I could mark them though I don't see a problem with that. Overall though to keep things simple (less bugs) might wontfix this.

**Comment by Maxwolf** [comment]
No need for this after looking at other games like fallout 4 where they do not indicate if it has been read. Figure this is good enough to not worry about this.
