### ISSUE TITLE
Glowing stuff on the wall at the start of Charon 

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#216]
I think I understand that this marks what we can break for loot? Only, the same glow has been on the things we've been meant to interact with up to this point, and we don't have a gun until shit goes south a minute or two from now. Might be a nitpick, but is there some way to flag them not to glow on this level until you locate and talk to the foreman?

**Comment by kallman1206** [comment]
![image](https://cloud.githubusercontent.com/assets/4227353/17679830/1bcac63e-62f2-11e6-8416-3a1e84f110c6.png)

**Comment by Maxwolf** [comment]
This makes perfect sense I can fix this so it will not glow until after the end of the world.

**Comment by Maxwolf** [comment]
Updated Charon to not have glowing shield generator before the end of the world. I use the start game region to correctly swap a real shield generator in the transform of the prop one and then delete the prop.
