### ISSUE TITLE
People milling about at the locked door on Charon

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#217]
They look pretty bizarre all sliding around going nowhere - are they there to draw our attention to get the "go get the keycard" memo?

**Comment by kallman1206** [comment]
Opened it now, and they still don't have places to be. Just dancing to the Musak, I see.

**Comment by Maxwolf** [comment]
They are customers walking around the store, but yeah it looks more like they are having seizures or dancing.

**Comment by Maxwolf** [comment]
Maybe I should just remove them from the store and have the static ones?

**Comment by kallman1206** [comment]
It's fine if they weren't all doing the potty dance in front of the door. Pacing a set path, or every few seconds picking a new way point to walk to that's further away than a step to the left or a jump to the right...

**Comment by Maxwolf** [comment]
Will improve the paths for our customers in the shopping area.

**Comment by Maxwolf** [comment]
Fixed!
