### ISSUE TITLE
White Keycard pedestal is a little goofy on Charon

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#218]
Can we have that be a few units lower? It feels like he left it on top of fridge or something.

**Comment by Maxwolf** [comment]
I will dress this room up more and place it on a table or something like how amber one is with american woman boss.

**Comment by kallman1206** [comment]
The caution a frames did seem out of place if it was meant to be an office, plus there were like half a dozen people in that closed off room, is there even door controls on the inside?

**Comment by Maxwolf** [comment]
The caution frames are placeholders, the are markers for me to know a room needs detail.

**Comment by Maxwolf** [comment]
There are no door controls on the inside, most of the doors are one way due to the linear nature of the game. I could put a switch on the other side of the door for visual purposes but don't want people closing it again after they open it.

**Comment by kallman1206** [comment]
It's just odd to think of them being trapped in there til you come by lol

**Comment by Maxwolf** [comment]
Hopefully can get to this tonight!

**Comment by Maxwolf** [comment]
Removed the guys from the back room so no longer are they being held hostage. Still have to place the objects down on the map before this can be closed.

**Comment by Maxwolf** [comment]
Fixed!

![image](https://cloud.githubusercontent.com/assets/6830398/19256692/451e88e2-8f1e-11e6-952a-331cd3033673.png)
