### ISSUE TITLE
Kicking this box around, though fun, is incredibly loud

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#219]
![image](https://cloud.githubusercontent.com/assets/4227353/17680044/276220d6-62f3-11e6-9c06-31e8f49f3f6a.png)

**Comment by Maxwolf** [comment]
Yeah their physics are messed up to if you shoot them they fly all over the place like nuts.

**Comment by Maxwolf** [comment]
Fixed! Box is heavier and sound softer
