### ISSUE TITLE
The walking sound is odd

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#22]
Nit pick: If my steps are that far between, my stride is fourteen feet long.

**Comment by kallman1206** [comment]
Which would be fine if I was supposed to be fifteen feet tall like you, Max, but the camera seems to suggest a mere 5-something like the NPCs.

**Comment by Maxwolf** [comment]
Ahahaha in the code it waits for you to move 4.2 meters before playing the
next sound o made it longer because it sounded really silly being close
together

I would not mind removing the step sounds honestly it always seems to be
out of place

**Comment by Maxwolf** [comment]
Changed up walking speed, made it not tick as much, and decreased overall speed of the player. There are probably more tweaks but this is much better than prototype that is for sure.
