### ISSUE TITLE
Too much music in the back of the Hypermarket

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#220]
The Musak and some other track are both playing at the same time in the warehouse behind the American Woman, and it's really cacophonic

**Comment by Maxwolf** [comment]
Ah! You are right my Oma is singing on the radio near foreman, I guess I could do a thing where I stop playing muzak when you get close to the foreman.

**Comment by Maxwolf** [comment]
Music is stopped when you enter the Forman's office.
