### ISSUE TITLE
Can't tell what direction I'm being shot from

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#221]
I know there's still an enemy, my health is going down and my HUD is full of meatloaf, but are they ahead or behind? :P

**Comment by Maxwolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6830398/17681677/fa2b877a-62fb-11e6-832b-78400eb4a2b1.png)

Need damage indicators to show what direction the fire came from.

**Comment by Maxwolf** [comment]
working on this today, will make graphics and regions on all sides of player to detect direction of damage.

**Comment by Maxwolf** [comment]
Make this so only Americans spawn on the levels, or make it so they are all on the same faction and shoot at the player.

Layer in ActionGameWindow.gui:
DirectionalDamage/DamageLeft
DirectionalDamage/DamageRight
DirectionalDamage/DamageTop
DirectionalDamage/DamageBottom

![image](https://cloud.githubusercontent.com/assets/6830398/19017921/0dd245e8-8804-11e6-9f0f-db1de38e9921.png)

**Comment by Maxwolf** [comment]
Finished! Got this working as intended!
