### ISSUE TITLE
Damage needs to be rebalanced (or I got incredibly unlucky)

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#222]
Some enemies I'd have to sit around all day getting shot in the vicinity of before they could take me down, others are seemingly armed with beige lasers of doom and get me from 100 to 0 in no time flat.

Hmm, maybe I was just caught in one of those tanks on the wall exploding and didn't in fact have full health to take that guy out to begin with?

**Comment by Maxwolf** [comment]
It could be that you was at low health from an attack and got nailed with something to finish you off. Some enemies like tazer guy do like 30 damage and leave you with very low health until it recharges.

Their health also varies, the chinese guy in metal suit takes like 10 bullets to put down (or one critical).

**Comment by kallman1206** [comment]
It totally was metal suit guy, was too used to a shotgun blast or two making tomato soup

**Comment by Maxwolf** [comment]
Added more health to the player. Increased from 100 to 500 to allow the player to get shot from about 5 different angles before they die.
