### ISSUE TITLE
FTL from FUEL3 to FUEL2 initially shows an incorrect distance

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#23]
I assume it's showing me the distance for each stop along the way, instead of the total distance to the location targeted? It just seems strange for it to claim 100 million miles, then jump to 700, etc.

Additionally, should I be allowed to shut off the fusion reactor while we're at FTL? I seem to recall us wanting to run out of water almost completely during this jaunt, but I only triggered the "water low" after arriving (and switching it back on). Did I do half the trip coasting on battery power? :)

**Comment by Maxwolf** [comment]
Yeah if you have enough battery power the reactor is not required. The machines require energy to function and the reactors purpose in life is to just fill the battery. Typically what happens is the reactor will die out and then battery drains and then the player is in real trouble.

As for the distance calculation I will show both. I want to show the total amount of miles to the current galactic target, and then show the current number of miles to the next location in the trip. I think this could be visually shown to the user as a set of graphics similar to the flight computer where we show the planets in a line and a marker for "You are here" moving from planet to planet as you travel.

Finally, yes, you can kill the reactor and even the FTL drive while you travel and it will disable the current trip. I don't know if these features will make it into the final game as they are quickly becoming rather useless in relation to the rest of the game mechanics.

**Comment by Maxwolf** [comment]
I will rework the FTL screen to show a line I think of planets and your current location so you can see like a icon of your ship moving towards your selected target destination from flight computer. Would be the same icons from flight computer but in a straight line from left to right with Pluto on the far right. Player would travel towards left side of the screen towards Earth.

Then the distances shown I can do both and overall percentage of trip completed. Sort of like a TomTom where when you arrive could even do some cheesy "You have arrived at your destination". Then when looking at that screen we could see distance to next target, total trip, and current percentage of the entire journey we have selected.

Overall I think this will make the experience of working with the FTL computer easier to understand and the distances traveled will have more meaning.

**Comment by Maxwolf** [comment]
I also removed the switch from the FTL drive so the player cannot turn it off mid-flight, and I removed the checkbox to allow you to stop at every location on the way to target. These changes in combination with the ones I mentioned above will let me close this issue.

**Comment by Maxwolf** [comment]
Since the flight computer, space stations, and some other places got removed there is not as much of this happening anymore. For example when you travel from Jupiter to Mars now there is no asteroid field anymore that you physically pass through so the distance shown is correct.

Marking this as complete since distances are correct, will make another issue for the reworking on screen to show distance to target.
