### ISSUE TITLE
GUI on Options Menu - Controls

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#26]
Have a checkbox to lock both the Horizontal and Vertical Mouse Sensitivity sliders when changing them.

Advanced users can un-check the lock checkbox and adjust both sliders independently.

**Comment by Maxwolf** [comment]
No problem, I can hook both of these together and put a checkbox below them to allow them to be changed independently. By default moving either of the sliders will make the other match it's value.

**Comment by Maxwolf** [comment]
Moving this to beta since it's not critical to the game and can be done when all other functionality is completed.

**Comment by Maxwolf** [comment]
Critical points in the game where characters are talking to the player do not have interruptions from enemy forces anymore. They are scripted and paced to prevent this problem.
