### ISSUE TITLE
Story Text Sound on Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#27]
The blip sounds playing during the player character text output should stop when the text stops animating.

**Comment by Maxwolf** [comment]
Yeah right now I just play a static sound ontop of the text like the voice-over for a character would work.  I could do a thing perhaps where I cancel the playing audio (would have to recode to to use it's own channel to do this).

Overall though yes, the player speaking jibbers should not keep playing after they are done talking. In reality we only need a couple blips from them to let the actual player know that their character is currently talking.

**Comment by Maxwolf** [comment]
Since we are not doing the players name and such and have a main character now we will begin the process of collecting all his dialog and then rigging each of those to sound files that do a single blip or computer talk until we get someone to act it out for us.

**Comment by Maxwolf** [comment]
Closing this now since the main character is fully voice acted by Breeze.
