### ISSUE TITLE
Charon Hypermarket Too Dark

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#30]
The arrival area should be well lit, at least to indicate direction.

**Comment by Maxwolf** [comment]
I will work on making this level brighter and more colorful with ads and bright lit rooms. I want the back of the market that is not public to be a little darker and more dirty than the front of the store but overall the player should always know where they are going.

**Comment by Maxwolf** [comment]
Fixed the color profile on my monitor and thus all the map lights. The entire game is now much brighter.
