### ISSUE TITLE
Gunplay on Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#33]
Without any indication of ammo counts, it's odd having to understand why the pistol seems endless ammo and the shotgun does not.

**Comment by Maxwolf** [comment]
The pistol is given to you when act 2 starts, it is fully loaded with 1000 rounds and yeah it feels like an endless supply of bullets. As much as I don't want any on-screen indicators for ammo counts like HUD I think we will have to do this along with health since players are confused about not dying and how much ammo is in their guns.

I will admit it also sucks when you go to kill a dude and the gun just dry fires. Very anti-climatic.

**Comment by kallman1206** [comment]
there might be a middle ground where it just says something like "Ammo: lots" until it drops below $amount. With my idea of "don't show me exactly how much health I have", maybe a similar "heap of bullets" image, where you only get an exact count below two dozen or some such. Though, for things like rockets or the lightning gun, exactly how many may work better.

**Comment by Maxwolf** [comment]
Ah okies, that way we don't know exactly how many rounds are in the pistol but we could show like an icon of a stack of bullets getting smaller and smaller.

**Comment by kallman1206** [comment]
Yeah. It's silly, and probably not truly workable, but I like the idea :P (Put an actual count on a pane of the PDA? Though, you wanted to be rid of inventory system in general, so who knows)

**Comment by Maxwolf** [comment]
I has an idea last night, was thinking I could show a picture of the guns sprite that you picked up in lower right corner and two progress bars. Then you could see how many bullets are in the gun right now, and how many bullets you have on your person to put into it but without telling you exactly how many and using the progress bar to so visual percentage.

**Comment by Maxwolf** [comment]
I modified one of the screenshots to show what I am talking about in regards to the sprite picture and progress bars. I moved it into the upper right corner so it doesn't lay ontop of the gun and block it.

![image](https://cloud.githubusercontent.com/assets/6830398/16394874/3310ba8a-3c6c-11e6-9b48-cf4aafcbdf3d.png)

**Comment by Maxwolf** [comment]
Fixed by adding nixie tube counters on hud for health, stamina, bullet count in gun, and total bullets on person.
