### ISSUE TITLE
Reload Times on Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#34]
The reload time is a bit slow at times; could be sped up a tiny bit.

**Comment by Maxwolf** [comment]
I can increase this speed, or make some system to let players upgrade themselves to increase reload time with that speed being the default. I am still torn if I should have enemies drop money that can be used to buy weapons and perks.

Alternatively I could just increase the speed without coding any other systems, would not mind it being faster. Right now each frame is on screen for about 0.3 seconds, could reduce this 0.25 or 0.1 to make it super fast.

**Comment by kallman1206** [comment]
The problem with making it a selectable perk is it tempts you down the road of designing and playtesting another dozen perks and the interactions between them and suddenly you have deus ex with a proficiency to resist poison where you only get poisoned in three rooms of the game.

**Comment by Maxwolf** [comment]
Damn you are right. Perks are cute but need to be designed around the content in the game, and the content that is used most. If I was going to do perks it would be for things like running speed, more stamina, reloading speed, hacking speed, etc.

Now that you mentioned that in last post I am seriously doubting the usefulness of such a system. Perhaps it is better to focus on what we have like gun-play and deep interaction with terminals and ship systems.

**Comment by kallman1206** [comment]
~200 days, too, y'know? :P

In an earlier design doc, you had mentioned some special guns, or special versions of guns. Maybe make doing the side missions where you loot them award you with that gun perk, like, "fires lightning faster" - instead of it being a skill thing, it's a loot thing. Work with the systems you have.

**Comment by Maxwolf** [comment]
Yeah I was originally not going to let enemies drop the plasma and lightning guns. Was going to make them special pickups on maps hidden behind lasers and force-fields in research laboratories.

**Comment by kallman1206** [comment]
It does seem odd that someone armed with the lightning gun can't stop us ;)

**Comment by Maxwolf** [comment]
Awesome, I will make this a thing for sure and enemies won't drop those weapons. This way when you find the lab where it is kept we can put tons of ammo around it for you to play with.

**Comment by Maxwolf** [comment]
Disabled the lighting gun and plasma rifle weapon and ammo drops from enemies so I can place them labs as special things.

**Comment by Maxwolf** [comment]
Fixed!
