### ISSUE TITLE
Teleporter Selection on Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#35]
After I select a teleporter location there is no visual indication of the location selected.

**Comment by Maxwolf** [comment]
I think maybe showing like a 'hologram' of the level geometry might be cool. Something like a wireframe mesh that just spins around that represents the area you are going to. I could make this apart of the GUI or something similar.

I agree though we need a better way to indicate to players they have engaged the teleporter and it is ready and awaiting your entry and indicates where you are going. Any thoughts or ideas on what this might/should look like?

**Comment by kallman1206** [comment]
1) light tube appears, isn't there when not dialed in
2) I'd like one of those red/green kitschy LED message boards that would have been high-tech at the time- http://bigledco.weebly.com/uploads/2/5/9/8/25985965/s112161711527934814_p10_i2_w1600.jpeg kind, with a marquee of the planet/ map name the teleporter is keyed into, mounted above and in front of the light tubes on a baffle of sorts? A different screen would be fine too, but one shouldn't have to load its interface to see what it's displaying.

**Comment by Maxwolf** [comment]
Hey man that is a great idea! I really like it. I can definitely do something like that. Can make it like a mix of that sign and a train station type board with location and where you are departing to once it's locked in. Yes I will also make it so those light tubes only turn on when you have something dialed in.

**Comment by Maxwolf** [comment]
Working on teleporter computer today, will integrate the scrolling sign into the design to show current location and current teleporter location. Will be on a bar scrolling across the top of the device so when you are standing on teleporter and face either direction you could see where you are going by looking at that sign or by looking at monitor on opposite side.

**Comment by Maxwolf** [comment]
Created a bunch of the signs and imported them into the engine as animated sprites on a single texture atalas.

![1df38bc9e4751775f5e2d26ac399dfa0](https://cloud.githubusercontent.com/assets/6830398/16651994/5c24fb4c-43fc-11e6-9ad4-f53bdc4ada52.gif)

![image](https://cloud.githubusercontent.com/assets/6830398/16652002/6c06dbf2-43fc-11e6-9c29-6bf2b90ae375.png)

**Comment by Maxwolf** [comment]
Done!

![d7abfa04461117daf026b0b0e2b21245](https://cloud.githubusercontent.com/assets/6830398/16680529/faeeaba4-44a3-11e6-9152-0eac32ebfec9.gif)

![81884335014113a3be7d7f111c4a3e02](https://cloud.githubusercontent.com/assets/6830398/16680531/fd763cc0-44a3-11e6-8488-915aa8f6d859.gif)

**Comment by kallman1206** [comment]
That's all I ever waned and more :)

**Comment by Maxwolf** [comment]
It was a really good suggestion! Looks great, thanks again.
