### ISSUE TITLE
Act 3 - Unlocking Doors

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#37]
More specific differentiation on which set of doors we are unlocking with which terminals.

Makes it easier to understand the logic behind the multiple typing of 'unlock'

**Comment by Maxwolf** [comment]
I could make the door terminal program a graphical program instead and do something like show the actual area where the door is. Could change up the typing of "unlock" to just be two buttons for lock and unlock.

With the graphical control I could do something like put a render target on the GUI to show the actual door in realtime that you would be unlocking. When you unlocked it could physically see it change color and unlock.

Another thing I could do is attach dynamic light that does not cast shadows to the door so it will emit a red light for locked and a green light for unlocked.

**Comment by Maxwolf** [comment]
Added keycards and access panels to mix this up so it's like computer, card, card, computer. I will modify the computers to be more verbose about what door they are exactly unlocking.

**Comment by Maxwolf** [comment]
Re-did most of the door program to be more verbose about the types of doors being unlocked. Added a cool unlocking sound and added to all consoles input sounds when the user is typing each one is different so not always the same type.

**Comment by Maxwolf** [comment]
Going to close this for now since the computer is now more verbose. This should serve it's purpose until we find or make something better.
