### ISSUE TITLE
PDA - Keyboard Control

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#38]
The TAB key should also close the PDA.

**Comment by Maxwolf** [comment]
Agree the tab key should indeed close the PDA. This was an oversight and definitely a bug that will be fixed for the Alpha. Code wise I need to hook the game controls manager from the PersonalDigitalAssistant.cs class and then use that to determine if the player is pressing the binded "PDA" key and then close the GUI control when that is intercepted.

**Comment by Maxwolf** [comment]
Done!
