### ISSUE TITLE
PDA - Information

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#39]
Put current Act information in the PDA

**Comment by Maxwolf** [comment]
At the bottom of the PDA I will print out the current act number, and total act numbers, and can even show a percent complete so players know they are 50% done with the game relative to the number of acts remaining.

**Comment by Maxwolf** [comment]
PDA shows current act information now.

![image](https://cloud.githubusercontent.com/assets/6830398/17197922/bd5fd33a-5425-11e6-934d-55a4807b990d.png)

**Comment by Maxwolf** [comment]
As does the tasks computer on the ships bridge. Marking this as complete now!

![image](https://cloud.githubusercontent.com/assets/6830398/17197928/cdccfd2e-5425-11e6-9cf3-039db2d73adf.png)
