### ISSUE TITLE
Guns in Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#41]
Make guns/items/ammo brighter to visually offset them from the background.

**Comment by Maxwolf** [comment]
I can do this for sure. I will make it so the items and weapons do not receive light or shadows, only ambient light so they will always be brighter than the surrounding map objects.

**Comment by Maxwolf** [comment]
Made weapons, ammo, and access cards not use be affected by lights or receive shadows. This means they will only take ambient light and always be brighter than their surroundings.
