### ISSUE TITLE
Towel

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#42]
Don't forget to bring your towel!

**Comment by Maxwolf** [comment]
There is going to be bathrooms on the stations and some showers. Needs to be soap jokes, towel jokes, and any other bathroom humor we want to mess with. It will be a good idea to reserve a room on each base for bathrooms easy low hanging fruit for filling them out.

**Comment by kallman1206** [comment]
@Maxwolf do you really not know the reference Fox is getting at? Do I need to bring over a DVD or point you to the arguably better radio play?

**Comment by kallman1206** [comment]
@FoxCouncil you definitely waited for this to be issue #42 as well, huh, Fox? Silly. I'm into it tho

**Comment by Maxwolf** [comment]
EhEhehe we had a towel in Incognito you could pick up too, gave you an achievement for bringing your towel. Clearly this is the most important issue.

**Comment by Maxwolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6830398/16636207/8e8faef4-438b-11e6-9914-70da7aea9729.png)

Mishen compree
