### ISSUE TITLE
Truck Odometer Should Show Some Miles On It Already

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#43]
The odometer should have some miles on it already or this is some kind of brand new truck?

**Comment by Maxwolf** [comment]
You are right the game starts with the truck at 0 miles on odometer. I could make it so there is some random amount of miles on there or choose some pre-made number. Since the ship left from Earth to Pluto at the start of the game we could put the number of miles between Earth -> Pluto as the starting distance.

**Comment by kallman1206** [comment]
I mean the place looks pretty new. Not so new as to not have multiple mouseholes, but maybe the type of mice prone to attack spaceships are just particularly expedient.

**Comment by Maxwolf** [comment]
I put way more trash around the ship like pizza boxes, beer cans, empty plates and dishes. This removes the new feeling a little more. I will have to lookup what distances are traveled from each point in the main quest and then make it so the odometer on the ship will reflect this.

So starting a new game has some random amount of miles on it. Then if you start from some act like 3 or 4 it would add to the random amount the amount you would have traveled in the main quest.

All of this together will give the impression you have traveled hundreds of millions of light years.

**Comment by Maxwolf** [comment]
Initial miles on truck: 8675309

![image](https://cloud.githubusercontent.com/assets/6830398/17390472/3cd84fa6-59c2-11e6-96da-18fefe926a9b.png)
