### ISSUE TITLE
Switch from Act 3 to Act 4

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#45]
The PDA has the correct task information; the screen on the bridge does not.

![Bug Screenshot](http://i.imgur.com/qEA7TZl.png)

**Comment by Maxwolf** [comment]
The task computer on the bridge is updating via event delegates and not actually checking every X number of seconds for new quest data. I will change this up so the bridge task computer program will check every 10 seconds for new quest data, that way it will update within a reasonable amount of time which the player will notice.

**Comment by Maxwolf** [comment]
Fixed tasks program on the bridge to update the current act data every time the underlying simulation modules tick that contain the story system. This fixes bug where bridge tasks would not match PDA tasks.
