### ISSUE TITLE
Sounds and Dialog

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#48]
The sound effect volume should duck under the dialog when the dialog is playing so the player can hear the dialog

**Comment by Maxwolf** [comment]
We should lower the general volume of the game to about half while voice-over item is playing, and then ramp it back up to normal value when the voice-over ends.I could do the same thing for the music so that nothing talks louder than the voice-over.

**Comment by Maxwolf** [comment]
Made voiceovers use the sound channel, need to make another one just for the voices and then I could make it louder or lower other sounds other than it.

**Comment by Maxwolf** [comment]
Moved this to beta since it is not causing problems with the game at this time and is not critical.
