### ISSUE TITLE
Mouse behaviour in Archimedes (may not be a bug)

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#49]
I was in the truck, and, seeing a train of mice, I endeavored to shoot them (with the shotgun). Two blasts and I killed one, but the remaining two abruptly changed course to run _towards_ me, to the other mousehole to the far left of the teleporter console.

This may just be me not understanding their AI, but... did I kill the mousehole object, maybe?

**Comment by Maxwolf** [comment]
Nope! You killed their friend and the dead body blocked their path in such a way that they calculated going to the other mouse hole was cheaper in terms of cost of number of moves.

I would write this off as you scaring them.
