### ISSUE TITLE
Profile management non-obvious when none exist

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#5]
When I went to start a new game, it took me to the profile screen, since I hadn't made one yet. It wasn't inherently obvious when I selected the new profile I'd need to click new game again. Is it possible to flag if you've sent someone there from the new game selection and open the new game menu when they do in face select their profile?

**Comment by Maxwolf** [comment]
Since we are doing a single player game now I might just get rid of the profile manager there is really no point to it anymore.

**Comment by Maxwolf** [comment]
Removed the profile manager from the game, named the player character Vladimir Gagarin and the ship the player travels on Vostok 42.
