### ISSUE TITLE
Charon neutral NPC's need to walk around

### ISSUE THREAD

**Issue by Maxwolf** [FoxBytes/SpaceTruckerBugs#52]
I want them moving around the store at random. I think a good way to do this is to make them good faction like the player and then create invisible enemies that spawn at random on the store shelves at random intervals when one is touched by one of the NPCs.

The idea here is that the neutrals will roam around the store killing "good deals" which are invisible enemies of another faction from them so their AI will target and move towards them. I will equip a special weapon to the NPC's called CreditCard that will fire invisible bullets at the invisible deals for them to "kill" them and make another spawn which will lead to this funny behavior or NPC's roaming around the store in groups trying to kill good deals with their credit card weapon.

**Comment by DarkGuardsman** [comment]
Not sure what the code looks like but that sounds hacky to do. Try implementing a track system were the NPCs roam around a pre-select series of paths. This will allow more control and help improve the flow of the visuals. Random systems tend to end up with NPCs walking into walls or the player.

**Comment by Maxwolf** [comment]
That is basically what they end up doing. The wording I used was tongue in cheek, when a invisible deal spawns they will use recast navigation system to draw a path to it and then start heading that way. Each NPC's does this on their own so they end up with unique paths.

**Comment by Maxwolf** [comment]
Done!
