### ISSUE TITLE
Consistency of in-game textures/text/dialogue/etc.

### ISSUE THREAD

**Issue by kyrofox** [FoxBytes/SpaceTruckerBugs#53]
- Padlock on select act screen looks lower res than text and screenshots. 
- No border around screenshots looks a bit off, possibly some sort of corner rounding or a border would help.
- Possibly, could add more hover feedback for hovering over acts on selection menu to parallel feedback from hovering over menu items (possibly highlight the words as well, or something)
- Maybe higher res cutscenes/intro video/loading screen (feels inconsistent, not to mention playing on 1080p screen)
- Resolutions between game textures are inconsistent sometimes http://i.imgur.com/DBbxapf.jpg
- inconsistency between text from main menu and font used in bottom left when starting the game
- When text appears, the voices do not follow at the same speed. When the robot first talks when you first move, his "noise" doesn't follow the text. with that style of text/voice I'm used to the text going at the exact same pace as the noises. (ex: undertale)
- starnav screen when hovering over planets just shows pure inverse of the image on hover. not consistent between the gas icons and the planet icons, could be nice to use same-size pixelated icons made by hand.

generally having everything with the same size textures and such, because consistency really provides to experience, and if everything fits into a single style, i feel like i can more easily get immersed in the world and appreciate it better. whenever I hit a bug or see an off texture, it kinda
brings me back to the real world and breaks the immersion

**Comment by Maxwolf** [comment]
These are all very good things for me to look into. Some of the items like loading screens are low-res on purpose I have a 1080p monitor (3840x2160) and test the game at 720p in a window (1920x10280). The problem there is the source images are based on stamps and other things from the 80's that were poor quality to start with.

The intro videos that play I could make them much higher resolution, but I kept them that way to match everything else mostly. The textures you pointed out I can fix, like the rat hole could make it have more pixels and not be so round would blend in more.

The starnav shows inverse image on opposite side, if you move around to other side it will be fine not a bug there just visual effect like the flight computer it projected up there. The icons that are on there would look better as pixel art I agree will keep that in mind.

I agree that consistency is key and adds to immersion. Thank you for all of your feedback I will be able to get most of these into the next build (Alpha) for December.

**Comment by Maxwolf** [comment]
Oh yeah forgot to mention the GUI's on monitors are not multisampled so I cannot change their resolutions to match everything else that is probably only thing I cannot actually fix due to the way it was coded from ground up.

**Comment by Maxwolf** [comment]
Fixed the undertale style voices for main character, he is now fully voiced like the other characters and has a name.

**Comment by Maxwolf** [comment]
Will redo the chapter select screen to have more feedback, get better screenshots and give them a border and then I will consider this issue closed.

**Comment by Maxwolf** [comment]
Forgot to mention the 16bit shader I have created and applied to the game that also helps tremendously

**Comment by Maxwolf** [comment]
Updated main menu. Better borders around the acts, and recent level pics

![image](https://cloud.githubusercontent.com/assets/6830398/17627770/4c0e27e2-6067-11e6-91da-fef3f32c68b1.png)
