### ISSUE TITLE
Ammo bar

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#56]
Really useful to have an ammo bar as the game keeps giving me guns with zero ammo. First level two shotguns are dropped and switched to automatically. Both seem to contain no ammo and clicking of empty can not always be heard over gun fire.

**Comment by Maxwolf** [comment]
I have already added nixie tubes to show health, stamina, current bullet count in gun, and total bullets in weapon. Here is an example of what it looks like.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6830398/16569712/47016a80-41ee-11e6-9ef8-f199852856f2.gif)

**Comment by DarkGuardsman** [comment]
That might work but still might be confusing.. we could do several different visuals that user can select in the settings.

**Comment by Maxwolf** [comment]
Yeah maybe we could put icons in tubes or something. For now this works good until we find something better.
