### ISSUE TITLE
AI always knows where the player is located

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#60]
Should be some level of confusion in AIs so every AI in a level doesn't path find to the player. This makes the game too easy as I can sit in a door and chicken shoot.

**Comment by Maxwolf** [comment]
Aye the AI is a basic implementation they have a navigation mesh they use
to see the world and make paths to vector points in it.

Not exactly my strong suite might look into middle ware for the AI to make
them not so stupid

**Comment by DarkGuardsman** [comment]
Once i learn the engine and code I might be able to help. AIs are something I do rather well in Minecraft right now, not sure if it will transfer to the engine.

**Comment by Maxwolf** [comment]
Gave you source code access as collaborator last night. Should let you start browsing around and seeing how it works on your own terms. Ask me anything will try to answer ASAP.

**Comment by Maxwolf** [comment]
Need to create some sort of patrol route object I can place on maps the enemies can use to roam to when they cannot find the player.

**Comment by DarkGuardsman** [comment]
Ya a little track path will work rather well for that.

**Comment by Maxwolf** [comment]
Implemented a lock and key system for rooms to make pacing a little nicer. Large areas of the map are more controlled as the player moves through them they must now clear all enemies in the area. The reasoning for this is a hostility type sensor excuse where the door remains locked until gunfire ceases.

The redone fight regions trigger more random and only when player is inside of them now. It doesn't work based on getting close to invisible region now entire areas of the map are sealed off and enemies will spawn at random points. Finally, some monster points are set to trigger right away as soon as the fight is started and player is present which will make it harder to just run by them.

Both of these changes half solve this problem of being able to chicken shoot the AI. Now you have to engage them to proceed in some circumstances to proceed to the next part of the game. The last of these changes will be to dramatically lower the health of the player and get death working.

**Comment by Maxwolf** [comment]
AI is working much better in these later builds, I am closing this now with confidence it is better now.
