### ISSUE TITLE
Copy Right issues

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#64]
A few elements of the game seem to reflect very closely to other medians. Namely the space truckers movie, and doom video game. Might want to double check everything is good before release to avoid major issues.

**Comment by DarkGuardsman** [comment]
I'm not going to lie, some of the textures look exactly like the old doom games :/ its a bit shocking in a bad way.

**Comment by Maxwolf** [comment]
Aye this is prototype lots of place holder graphics and sounds from other games right now. For example the main menu is actually FROM the Space Truckers movie. Waiting on Prowler to redo it with a model to replace that with our own.

The textures on walls and such are not from any other games but my own. All of the sprite enemies and weapons are from Doom WADS for now until we can get our own made from models or actual models.

Also, never lie ;)

**Comment by DarkGuardsman** [comment]
Ya I don't lie but sometimes I like to hint at things to get people to figure it out themselves. I find it better than telling them the true answer right away. That being said the graphics are working even though they are from another game lol.

**Comment by Maxwolf** [comment]
Closing this since we don't intend to have stolen content in the game on launch. I will be removing the place holder things one by one as we get replacements for them. Right now it's the sprite enemies, guns, keycards, some sounds, and all the music.
