### ISSUE TITLE
Add a journal to the ship for backstory

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#65]
Would be useful to look back on story pieces as well get the back story of the character. After all I had no clue what nation the character was causing confusion when Americans wanted to kill me.

**Comment by Maxwolf** [comment]
On the PDA there is a chat history, but yeah we need more lore and explanation about your place in the world and what is going on. There will also be computer terminals you can access which have lore drops in the form of log files you can read/interact with to give even more back story for players that want it.

**Comment by DarkGuardsman** [comment]
Computer will help but also add some random items in the ship. Like picture of his family since the character cries out "You killed my family and friends" in the nix station. If feels a bit disconnected when you don't know the backstory of the character.

**Comment by Maxwolf** [comment]
Will add one of the log file computers to the ship so we can put logs in there about past missions, explain what happened to past crew, who Ugly is, why you out for so long. Will be good place to drop lots of that information for players that want it.

**Comment by Maxwolf** [comment]
Added two computer consoles that are russian based. Named them from left to right ships log for like a diary from Vlad himself and log book for previous jobs to give a sense that he has been doing this for a while.

![image](https://cloud.githubusercontent.com/assets/6830398/16707666/6a3be00c-458b-11e6-8812-a1a473c5cf35.png)

**Comment by Maxwolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6830398/16717403/8ac09562-46ca-11e6-89bc-30e37f40324c.png)
