### ISSUE TITLE
Weapon selection menu/bar

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#67]
When hitting number keys I should see a weapon selection menu pop up. Something like half life two's style when each number key has several weapons.

As well a bar at the bottom should show what key goes to what weapon.

**Comment by Maxwolf** [comment]
Something like this from Half-Life 1? Could press button or mouse-wheel to select the menu items.

![image](https://cloud.githubusercontent.com/assets/6830398/16569250/fb7c7db6-41e8-11e6-84df-687794966710.png)

**Comment by DarkGuardsman** [comment]
yes, might also be useful to use the hp bar as well from that shot.

**Comment by Maxwolf** [comment]
Moving this to beta since Valve made this because they had more than 10 weapons. Since I only have 9 there is no need for this. I will re-visit this issue if people have problems knowing ammo counts in the alpha with the new nixie tube ammo counters.

**Comment by Maxwolf** [comment]
Not required at this time, we have 10 weapons counting the PDA.
