### ISSUE TITLE
Where is the ship name used?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#7]
Zoning into the ship it tells me it's the Archimedes regardless of what I've named it; unless that's its class or some such?

**Comment by kallman1206** [comment]
OK, I see that that's credits now, my bad >.>

**Comment by kallman1206** [comment]
Then again, "Archimedes Engineering" shows up every time you zone in to the truck, in the same way the base names do, so I'm not retracting it as an issue regardless ;) Map name?

**Comment by Maxwolf** [comment]
Yeah that is the map name great idea to make it use the name you gave the
ship I will do that I. Alpha for sure

**Comment by kallman1206** [comment]
Oh, but! If you're planning to remove profiles then we never actually do name the ship, so whether I want to call it the Fancy Pants V or not is irrelevant.

**Comment by Maxwolf** [comment]
Ah you are right I am not thinking this all the way through. If I removed the player manager I would have to call the player something and then use that name instead of you. Maybe that would be a good idea? Or do you like the idea that I make your player character talk?

**Comment by kallman1206** [comment]
Silent protagonist is played to death, makes for stilted dialog choices. Half life 3 isn't delayed because of technical reasons, they just can't think of how to talk to impossibly stoic Gord anymore.

**Comment by Maxwolf** [comment]
Alright I will leave it be then and modify the profile menu to look like the other menus on the main menu. I will make it so when you enter your ship it uses your ship name from profile manager.

**Comment by Maxwolf** [comment]
Made it so the players ship name is used in the title card sequence. It detects the old name and replaces it.

![image](https://cloud.githubusercontent.com/assets/6830398/16574051/9f43ef74-422f-11e6-9a17-1182b5b5cafd.png)
