### ISSUE TITLE
Print screen doesn't work

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#71]
I tried to take a screen shot which should normally be capture by dropbox. The key command seems to not go threw to dropbox outside of the game. As well doing ctrl+v into paint results in a black screen for the shot.

**Comment by Maxwolf** [comment]
F12 is screenshot key, will save to AppData\Local\Space Trucker\Screenshots

**Comment by DarkGuardsman** [comment]
ah, might want to add some indication in game that it took the shot. At least on the non-steam version.

**Comment by Maxwolf** [comment]
I could do that for sure and make it play some noise or something like that. The only indication this has happened right now is on the PDA history panel it mentions the screenshot was taken and the location it was saved but this is not obvious at first.

**Comment by Maxwolf** [comment]
Did some experiments. Full screen the print screen button will do nothing, but if in a window and you press print screen it will work. You can even Alt+PrintScreen to take just the currently focused window.

**Comment by Maxwolf** [comment]
Closing this since behavior of screenshots is normal. Once the game is on steam it has it's own notifications for this.
