### ISSUE TITLE
NPC scientists that give weapons

### ISSUE THREAD

**Issue by Maxwolf** [FoxBytes/SpaceTruckerBugs#73]
This would be a reward for the player not killing the NPC scientists I can place in labs, they can give the player weapons like the lightning gun or plasma rifle which they normally could not get otherwise. I think this would be a cool way for the player to obtain these weapons.

**Comment by Maxwolf** [comment]
Make them both sound like scientists who are scared and just avoided getting killed and want to help you because you are not American.

Line 1: "Thank you for saving me, here take this you can use it more than me."
Line 2: "It's dangerous to go alone, take this and give them hell!"

**Comment by DarkGuardsman** [comment]
What nationality/accent for the lines?

**Comment by Maxwolf** [comment]
American! All the bases we goto are American owned and operated

**Comment by DarkGuardsman** [comment]
k, would be interesting to add a range of nationalities though

**Comment by Maxwolf** [comment]
We had much more and chinese, russian bases in the beginning but scale back due to scope creep. With some 200 days until gold it is best to focus on the main quest and no additional elements.

I will save that for DLC and addons if the game does well at market.

**Comment by DarkGuardsman** [comment]
Ya, just was thinking for lines as your could in theory have a guy from china who is an American

**Comment by Maxwolf** [comment]
Imported the audio @DarkGuardsman gave me, it ended up being 4 lines that I placed into scientist folder under voice acting. Made a class for them called FriendlyScientist which pics one of the lines. I named them after plasma rifle and lightning gun, and rocket launcher for what they give you when you interact with them and they "Die()" into standard NPC which the other units will target as enemy.

**Comment by Maxwolf** [comment]
Video of the NPC's in action and how they look on levels to player.
https://www.youtube.com/watch?v=prwJ7DdQsxo
