### ISSUE TITLE
Cache several logs

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#79]
Logs should be saved with the time the game was started. This way several log files can be stored over time and saved for analyzing at a later date.

As well only 20~ logs should be kept to avoid wasting file space.

**Comment by Maxwolf** [comment]
Yeah when the engine is deployed it will not create log files like that. When it's in debug mode like this it will create warnings, pop up the console, and generally complain about anything and everything.

**Comment by DarkGuardsman** [comment]
TBH we should consider modifying the engine at some point, because I keep hearing it has limitation. However, I remember you saying we had access to it's source code.

**Comment by Maxwolf** [comment]
That is not something to be taken lightly. Every engine has limitations and this is normal, part of the fun is working within constraints that is what makes this fun.

We do not have full source code to this engine. It is NeoAxis 3.3, previous versions of the engine like 0.8x and 1.2 I had full source code access and that was used on Incognito and SickBrick.

**Comment by Maxwolf** [comment]
The logging mechanism can be changed though of course, I am talking about things like access to rendering engine which is all C++ anyway.

**Comment by Maxwolf** [comment]
Closing this since behavior of log files is normal. Date on the files is when crash occurred, Game.log is overwritten each time the project is started. During deployment this does not happen.
