### ISSUE TITLE
After using FTL water continues to be drained, and, in fact, gets used up completely

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#8]
Not sure if it's intentional that we have no fuel shortly after arriving at Charon, but my just loitering around writing these bugs seems to have emptied my tanks.

I turned off all ship lights with the console before heading to the teleporter, and while I was mentioning its weird hitbox the alarms went off.

Seems strange Ugly would send us off from his fuel station running on fumes, especially if we are doing a job for him and getting fed on his dime ;)

**Comment by Maxwolf** [comment]
I am even thinking of disabling the water mechanic and making it all scripted so you have X amount of water per act and it will change based on where you are and what you are doing. The alternative is to just make it so every place you visit fills you up.

**Comment by Maxwolf** [comment]
Quadrupled the amount of water in the tank by default, it can still run out but this combined with the tutorial to help players along should prevent this from happening during 'normal' play.
