### ISSUE TITLE
Setting - Screen shot save location

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#80]

**Comment by Maxwolf** [comment]
Screenshot location for deployed game project is as follows:
**C:\Users\<username>\AppData\Roaming\SpaceTrucker\Screenshots**

There is no need to let the user change this, and doing so would introduce bugs where they could set it to a location on their drive to which they don't have permission. It is easier for the user to move the screenshots out of this directory into their dropbox, telegram, skype, google drive, tumblr, etc.
