### ISSUE TITLE
What's with the guy calling for help in the back of the hypermarket?

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#9]
He's just kind of around, writhing on the ground, asking me to "Kill me now" "make it stop" "let me out" "asfsjfagkahfdkg". "The horror", indeed. Nothing's even happened yet, guy! Makes some sense _after_ the world ends but what the heckles.

**Comment by Maxwolf** [comment]
These guys serve no purpose at all. My original intention was to make it seem like the Americans are doing weird shit to people but it doesn't work here I will save these sick sprite people for some other base and put them on medical tables or something will make much more sense then.

**Comment by Maxwolf** [comment]
Removed these people.
